server:
  port: 18081

spring:
  application:
    name: order
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/order
    username: root
    password: 1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  cloud:
    function:
      definition: orderChangeStatus;
    stream:
      bindings:
        domainEventPublish-out-0:
          binder: kafka
          destination: domain-event-publish
        orderCreated-out-0:
          binder: kafka
          destination: order-created
        orderChangeStatus-in-0:
          binder: kafka
          destination: order-status-change
          group: local_order_status_change
      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            max.poll.records: 1
            max.poll.interval.ms: 600000
            auto.offset.reset: latest

